import argparse
import json
import os
import sys
import yaml

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_PROJECT_ROOT, "src"))

from search_agent.llm_gemini import call_gemini

JUDGE_PROMPT_TEMPLATE = """You are an expert AI judge evaluating a search-augmented agent's query fanout generation.

Evaluate the fanout branches generated by the agent. You must return your evaluation as a strict JSON object. Do not include markdown formatting like ```json or any other text outside the JSON object.

Input Data:
User Query: {query}
Persona: {persona}
Task Type: {task_type}
Task Category: {task_category}
Search Required: {search_required}
Expected Personalization Stage: {expected_personalization_stage}
Persona Relevant Dimensions: {persona_relevant_dimensions}

Generated Fanout Branches to Evaluate:
{fanout_branches}

Metrics to score on a 1-5 scale:
- persona_field_use: Does the fan-out use the relevant persona constraints? (Higher is better)
- query_specificity: Are the subqueries specific enough to retrieve useful evidence? (Higher is better)
- query_diversity: Do the subqueries cover meaningfully different aspects? (Higher is better)
- search_realism: Do the subqueries look like realistic search queries? (Higher is better)
- faithfulness_to_user_query: Do the subqueries preserve the original user intent? (Higher is better)
- overpersonalization_risk: Do the subqueries overuse irrelevant persona details? (1 = no problematic overpersonalization, 5 = severe overpersonalization)

Important Instructions:
Do not reward a fan-out merely because it repeats persona words. Reward only persona usage that is relevant to the original query.
For retrieval_sensitive tasks, reward fan-out that translates relevant persona constraints into useful search queries.
For synthesis_sensitive tasks, do not require heavy persona-specific fan-out. Reward faithful, search-worthy, evidence-grounding queries. Penalize fan-out that over-personalizes by narrowing the search away from the user's actual information need.

Your output MUST be exactly in this JSON format:
{{
  "scores": {{
    "persona_field_use": 1,
    "query_specificity": 1,
    "query_diversity": 1,
    "search_realism": 1,
    "faithfulness_to_user_query": 1,
    "overpersonalization_risk": 1
  }},
  "rationale": {{
    "persona_field_use": "...",
    "query_specificity": "...",
    "query_diversity": "...",
    "search_realism": "...",
    "faithfulness_to_user_query": "...",
    "overpersonalization_risk": "..."
  }}
}}
"""

def clean_json_response(text: str) -> str:
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()

def evaluate_fanout(run, config, model="gemini-flash-latest"):
    prompt = JUDGE_PROMPT_TEMPLATE.format(
        query=run.get("user_query", run.get("query", "")),
        persona=json.dumps(run.get("persona", {}), indent=2),
        task_type=run.get("task_type", "unknown"),
        task_category=run.get("task_category", "unknown"),
        search_required=run.get("search_required", True),
        expected_personalization_stage=run.get("expected_personalization_stage", "unknown"),
        persona_relevant_dimensions=run.get("persona_relevant_dimensions", []),
        fanout_branches=json.dumps(run.get("fanout_branches", []), indent=2)
    )
    
    result = {
        "run_id": run.get("run_id", "unknown"),
        "experiment_name": run.get("experiment_name", "unknown"),
        "variant": run.get("variant", "unknown"),
        "persona_id": run.get("persona_id", "unknown"),
        "query_id": run.get("query_id", "unknown"),
        "task_type": run.get("task_type", "unknown"),
        "task_category": run.get("task_category", "unknown"),
    }
    
    try:
        response = call_gemini(prompt, model=model, temperature=0.1)
        response_json = json.loads(clean_json_response(response))
        if "scores" not in response_json or "rationale" not in response_json:
            raise ValueError("Missing 'scores' or 'rationale' in JSON output.")
        result["scores"] = response_json["scores"]
        result["rationale"] = response_json["rationale"]
    except Exception as e:
        result["error"] = str(e)
        result["scores"] = {}
        result["rationale"] = {}
        
    return result

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--model", type=str, default="gemini-flash-latest")
    args = parser.parse_args()

    with open(args.config, "r") as f:
        config = yaml.safe_load(f)
        
    runs_path = config.get("outputs", {}).get("runs_path")
    out_path = config.get("outputs", {}).get("fanout_scores_path")
    
    if not os.path.isabs(runs_path): runs_path = os.path.join(_PROJECT_ROOT, runs_path)
    if not os.path.isabs(out_path): out_path = os.path.join(_PROJECT_ROOT, out_path)
    
    if not os.path.exists(runs_path):
        print(f"Error: Runs file not found at {runs_path}")
        sys.exit(1)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    
    runs = []
    with open(runs_path, "r") as f:
        for line in f:
            if line.strip():
                runs.append(json.loads(line))
                
    if args.limit:
        runs = runs[:args.limit]
        
    import time
    from concurrent.futures import ThreadPoolExecutor, as_completed

    evaluator_rpm = 250
    evaluator_max_workers = 15
    pacing_delay = 60.0 / evaluator_rpm

    results_map = {}
    
    with ThreadPoolExecutor(max_workers=evaluator_max_workers) as executor:
        future_to_idx = {}
        for idx, run in enumerate(runs):
            if "fanout_branches" in run and len(run["fanout_branches"]) > 0:
                print(f"Submitting fanout evaluation {idx+1}/{len(runs)} (run_id: {run.get('run_id')})...")
                future = executor.submit(evaluate_fanout, run, config, args.model)
                future_to_idx[future] = idx
                time.sleep(pacing_delay)
                
        for future in as_completed(future_to_idx):
            idx = future_to_idx[future]
            try:
                res = future.result()
                results_map[idx] = res
                print(f"Completed fanout evaluation {idx+1}/{len(runs)} (run_id: {res.get('run_id')}).")
            except Exception as e:
                print(f"Error in fanout evaluation {idx+1}: {e}")
                
    results = [results_map[k] for k in sorted(results_map.keys())]
        
    with open(out_path, "w") as f:
        for r in results:
            f.write(json.dumps(r) + "\n")
            
    print(f"Evaluated {len(results)} runs. Fanout scores saved to {out_path}")

if __name__ == "__main__":
    main()
