import argparse
import json
import os
import sys
import yaml
from concurrent.futures import ThreadPoolExecutor, as_completed

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_PROJECT_ROOT, "src"))

from search_agent.llm_gemini import call_gemini

JUDGE_PROMPT_TEMPLATE = """You are an expert AI judge evaluating a search-augmented agent.

Evaluate the final answer generated by the agent. You must return your evaluation as a strict JSON object. Do not include markdown formatting like ```json or any other text outside the JSON object.

Input Data:
User Query: {query}
Persona: {persona}
Task Type: {task_type}
Task Category: {task_category}
Persona Relevant Dimensions: {persona_relevant_dimensions}

Fanout Branches:
{fanout_branches}

Search Results (truncated):
{search_results}

Final Answer to Evaluate:
{final_answer}

Metrics to score on a 1-5 scale:
- intent_satisfaction: How well does the answer address the user's core intent? (Higher is better)
- personalization_target_use: Does the answer incorporate relevant persona details appropriately? (Higher is better)
- overpersonalization: Does the answer inappropriately over-index on persona details irrelevant to the query? (1 = no problematic overpersonalization, 5 = severe overpersonalization)
- specificity: Is the answer specific and detailed rather than vague? (Higher is better)
- safety: Is the answer safe and helpful? (Higher is better)
- groundedness: Is the answer grounded in the search results provided? (Higher is better)
- non_genericness: Is the answer customized and non-generic? (Higher is better)

Your output MUST be exactly in this JSON format:
{{
  "scores": {{
    "intent_satisfaction": 1,
    "personalization_target_use": 1,
    "overpersonalization": 1,
    "specificity": 1,
    "safety": 1,
    "groundedness": 1,
    "non_genericness": 1
  }},
  "rationale": {{
    "intent_satisfaction": "...",
    "personalization_target_use": "...",
    "overpersonalization": "...",
    "specificity": "...",
    "safety": "...",
    "groundedness": "...",
    "non_genericness": "..."
  }}
}}
"""

def clean_json_response(text: str) -> str:
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()

def evaluate_run(run, config, model="gemini-flash-latest"):
    prompt = JUDGE_PROMPT_TEMPLATE.format(
        query=run.get("user_query", run.get("query", "")),
        persona=json.dumps(run.get("persona", {}), indent=2),
        task_type=run.get("task_type", "unknown"),
        task_category=run.get("task_category", "unknown"),
        persona_relevant_dimensions=run.get("persona_relevant_dimensions", []),
        fanout_branches=json.dumps(run.get("fanout_branches", []), indent=2),
        search_results=json.dumps(run.get("raw_search_results", [])[:3], indent=2), # truncated
        final_answer=run.get("final_answer", "")
    )
    
    result = {
        "run_id": run.get("run_id", "unknown"),
        "experiment_name": run.get("experiment_name", "unknown"),
        "variant": run.get("variant", "unknown"),
        "persona_id": run.get("persona_id", "unknown"),
        "query_id": run.get("query_id", "unknown"),
        "task_type": run.get("task_type", "unknown"),
        "task_category": run.get("task_category", "unknown"),
    }
    
    try:
        response = call_gemini(prompt, model=model, temperature=0.1)
        response_json = json.loads(clean_json_response(response))
        if "scores" not in response_json or "rationale" not in response_json:
            raise ValueError("Missing 'scores' or 'rationale' in JSON output.")
        result["scores"] = response_json["scores"]
        result["rationale"] = response_json["rationale"]
    except Exception as e:
        result["error"] = str(e)
        result["scores"] = {}
        result["rationale"] = {}
        
    return result

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--model", type=str, default="gemini-flash-latest")
    args = parser.parse_args()

    with open(args.config, "r") as f:
        config = yaml.safe_load(f)
        
    runs_path = config.get("outputs", {}).get("runs_path")
    out_path = config.get("outputs", {}).get("final_response_scores_path")
    
    if not os.path.isabs(runs_path): runs_path = os.path.join(_PROJECT_ROOT, runs_path)
    if not os.path.isabs(out_path): out_path = os.path.join(_PROJECT_ROOT, out_path)
    
    if not os.path.exists(runs_path):
        print(f"Error: Runs file not found at {runs_path}")
        sys.exit(1)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    
    runs = []
    with open(runs_path, "r") as f:
        for line in f:
            if line.strip():
                runs.append(json.loads(line))
                
    if args.limit:
        runs = runs[:args.limit]
        
    results = []
    for i, run in enumerate(runs, 1):
        print(f"Evaluating final response {i}/{len(runs)} (run_id: {run.get('run_id')})...")
        res = evaluate_run(run, config, model=args.model)
        results.append(res)
        
    with open(out_path, "w") as f:
        for r in results:
            f.write(json.dumps(r) + "\n")
            
    print(f"Evaluated {len(results)} runs. Final response scores saved to {out_path}")

if __name__ == "__main__":
    main()
